### ISSUE TITLE
Server Error 500 after Auth

### ISSUE THREAD

**Issue by genem2** [black-roland/homeassistant-microsoft-todo#15]
I think I've followed all instructions properly, but: Once I click on Link Microsoft To Do account to initiate the link, I sign into MS fine, but then I get:

500 Internal Server Error
Server got itself in trouble

The URL in the browser at that time is 
https://MY_DOMAIN/api/microsoft-todo?code=M65....&state=4Y0Z.....

Suggestions?
Thank you ... Really looking forward to this functionality.

**Comment by black-roland** [comment]
@genem2 Could you share the error from the log file? The log file can be found in the config directory as [`home-assistant.log`](https://www.home-assistant.io/integrations/logger/#service-set_level).

This would help me to investigate the issue. Thanks.

**Comment by genem2** [comment]
So sorry, didn't take notice of that.

Here you go:

```
2019-12-13 05:53:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 218, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 231, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 278, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 908, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 695, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2019-12-13 05:54:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 120, in handle
    result = handler(request, **request.match_info)
  File "/config/custom_components/microsoft_todo/calendar.py", line 155, in get
    token = self.oauth.fetch_token(TOKEN_URL, client_secret=self.client_secret, code=data.get("code"))
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS90023: Public clients can't send a client secret.
Trace ID: b033110a-a7cb-44a8-9d8f-dc1fca680c00
Correlation ID: 1eda0d62-5f59-4421-be75-b65ffef9f922
Timestamp: 2019-12-13 13:54:34Z

```

**Comment by genem2** [comment]
Not sure if this is relevant, but in the Azure config, I had to sent my redirect URI to **Type:** Public client/native (mobile & desktop). 

My HA is running Dockered in unRAID, so my browser will not reach it using localhost.  Using the server's IP (http://192.168.0.3:8123/api/microsoft-todo) will no longer work as it did in your video, since the Azure UI changed and doesn't allow http, except for http://localhost.

I guess my only other option is to restart the unRAID server with a local UI and use some browser there to be on http://localhost....

**Update:** That theory worked, and the auth pop-up reported: Microsoft To Do has been successfully authorized! You can close this window now!

But, upon return, the **I authorized successfully** button does nothing. 
Entity: **configure.microsoft_to_do** remains as **configure**.

**Update 2:** I can't explain, but I noticed the next day, that this was all working all of a sudden. It must have saved off something from the above test. This seemed to work great for a few days, but it appears that I can only add new items to specific lists. I'll fork that off separately.

**Comment by black-roland** [comment]
> Not sure if this is relevant, but in the Azure config, I had to sent my redirect URI to **Type:** Public client/native (mobile & desktop).

I haven't checked if it works with client/native but could you please try with the web API?

> But, upon return, the I authorized successfully button does nothing.
> Entity: configure.microsoft_to_do remains as configure.

Yeah, it seems this bug #10 :( But the message should disappear after the restart.

**Comment by black-roland** [comment]
I haven't heard from you for a while so I'm closing this issue. But please feel free to reopen if you still have this issue.
