### ISSUE TITLE
Error Handaling Request

### ISSUE THREAD

**Issue by Slittle82** [black-roland/homeassistant-microsoft-todo#30]
I'm getting the following error in the logs after trying to configure.  Any ideas?

Logger: aiohttp.server
Source: custom_components/microsoft_todo/calendar.py:171
First occurred: 11:22:56 AM (1 occurrences)
Last logged: 11:22:56 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 122, in handle
    result = handler(request, **request.match_info)
  File "/config/custom_components/microsoft_todo/calendar.py", line 171, in get
    code=data.get("code")
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS9002331: Application '93e1e785-2885-4f1f-ab4e-4dd194cc27a5'(Home Assistant) is configured for use by Microsoft Account users only. Please use the /consumers endpoint to serve this request.
Trace ID: 902f662d-4b03-4cfb-93cf-6ee3af240900
Correlation ID: 1220aea5-7bc4-456b-a79c-ca5baf624fb3
Timestamp: 2020-05-08 10:22:56Z

**Comment by Slittle82** [comment]
Checked the resolved list and fixed by changing to work and personal
