### ISSUE TITLE
To do plugin authentication token errors

### ISSUE THREAD

**Issue by gfcondeco** [black-roland/homeassistant-microsoft-todo#36]
Hello,

Recently to do plugin started with the errors below:

2020-09-27 18:24:25 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up microsoft_todo platform for calendar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 394, in request
    url, headers, data = self._client.add_token(url,
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/microsoft_todo/calendar.py", line 127, in setup_platform
    todo_lists = tasks_api.get_lists()["value"]
  File "/config/custom_components/microsoft_todo/outlook_tasks_api.py", line 95, in get_lists
    res = self.client.get(uri, params=query_params)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 407, in request
    token = self.refresh_token(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 374, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) AADSTS70000: The provided value for the input parameter 'refresh_token' or 'assertion' is not valid. The token was issued for a different client id
Trace ID: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
Correlation ID: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
Timestamp: 2020-09-27 17:24:23Z

Any idea?

Thank you.

**Comment by Luukxt8** [comment]
Hi, I have the same errors. Is this integration still being worked on?
@black-roland

**Comment by Luukxt8** [comment]
@gfcondeco, Try to find the file **.ms_todo_auth.json** in your home assistant folder and delete it. After deletion you can restart Home Assistant. This fixed it for me.

**Comment by gfcondeco** [comment]
@Luukxt8 thank you!! it's working now! =)

**Comment by black-roland** [comment]
Oh, sorry for the delay in replying. But I'm glad the problem is solved :slightly_smiling_face: Thanks.
