### ISSUE TITLE
Feature Request: Shared Lists / List Groups

### ISSUE THREAD

**Issue by jeronsanders** [black-roland/homeassistant-microsoft-todo#48]
Is it possible to add the ability to see shared lists? Currently I can see my own lists, but I cannot see lists shared between my wife and I as list groups.

**Comment by aetha** [comment]
Seconding this. I *can* see calendar entities appearing for shared lists, but their items are not being synced. I think the `Tasks.ReadWrite.Shared` scope just needs to be added in auth, (in addition to `Tasks.ReadWrite`).

**Comment by aetha** [comment]
Yikes, this is more than just a feature request, there’s a nasty bug behind this too. Just looked at my log, and it’s exploded with errors. Without that scope, attempts sync my shared lists are failing, and immediately retried, resulting in a constant flood of requests. Here’s one of them.

```
2021-04-12 21:51:12 ERROR (SyncWorker_11) [custom_components.microsoft_todo.calendar] Unable to get tasks: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/beta/me/outlook/taskFolders/xxx=/tasks?%24filter=status+ne+%27completed%27&%24top=100. Response: {'error': {'code': 'InvalidAuthenticationToken', 'message': 'CompactToken validation failed with reason code: 80049228.', 'innerError': {'date': '2021-04-12T11:51:12', 'request-id': 'xxx', 'client-request-id': 'xxx'}}}
2021-04-12 21:51:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.homewarez fails
Traceback (most recent call last):
File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
await self.async_device_update()
File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 490, in async_device_update
raise exc
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/opt/homeassistant/lib/python3.8/site-packages/homeassistant/util/__init__.py", line 278, in wrapper
result = method(*args, **kwargs)
File "/home/ha-arcana/.homeassistant/custom_components/microsoft_todo/calendar.py", line 221, in update
tasks_res = self._tasks_api.get_uncompleted_tasks(self._list_id)
File "/home/ha-arcana/.homeassistant/custom_components/microsoft_todo/outlook_tasks_api.py", line 65, in get_uncompleted_tasks
res.raise_for_status()
File "/opt/homeassistant/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/beta/me/outlook/taskFolders/xxx=/tasks?%24filter=status+ne+%27completed%27&%24top=100
```

**Comment by aetha** [comment]
Got round to fixing this myself.

**Comment by rasssta** [comment]
Not sure if this was actually solved? I can still only see my own lists and the ones I've created and shared with others, but not lists that are shared with me and created by someone else.

**Comment by rasssta** [comment]
I've tried to remove the .ms_todo_auth.json file and re-authenticate. Same issue.

**Comment by aetha** [comment]
Wrote this in the wrong issue, copypasting it here:

Not sure but it's possible you might need to reauthenticate your account. 

If you want to try that: in your Hass config directory, try deleting or renaming your `.ms_todo_auth.json`. Restart Home Assistant and set up your account again.

**Comment by aetha** [comment]
@rasssta Do you know whether you're updated to 1.0.3? ~~I'm actually not sure if this repository is set up to update correctly or not.~~

Edit: nvm, should work, just confused cos HACS doesn’t tell me the current version. Anyways, I think I know the other thing I had to do to make it work. You gotta add the correct permission in the Azure portal.
![E0DA6B33-C968-4A38-BBB9-0433DB1E5D22](https://user-images.githubusercontent.com/3007450/115944444-233dd980-a4f9-11eb-9275-b9fbc22c9293.jpeg)

Navigate to this page, then Add a permission > Microsoft Graph > Delegated permissions > search for ‘tasks’ > tick ‘Tasks.ReadWrite.Shared’, and finally click ‘Add permissions’.

**Comment by aetha** [comment]
I’m not 100% sure rn, but if that turns out to be the missing step, we should add it to the README.

**Comment by rasssta** [comment]
Yes, running 1.0.3.

I've tried to add Tasks.ReadWriteShared as well but that doesn't work. I think that permission is explicitly for your own tasks that you've shared (and not non-shared), not tasks being shared with you.
